# Code for get txt with 200 mountain names

In [ ]:
!pip install pandas
import pandas as pd

In [ ]:
df = pd.read_csv("Mountain.csv")
df.head()

,Mountain,Metres,Feet,Range,Location
0,Mount Everest,8848.0,29029,Himalayas,Nepal/China
1,K2,8612.0,28255,Karakoram,Pakistan/China
2,Kangchenjunga,8586.0,28169,Himalayas,Nepal/India
3,Lhotse,8516.0,27940,Himalayas,Nepal – Climbers ascend Lhotse Face in climbin...
4,Makalu,8485.0,27838,Himalayas,Nepal

## Choose 200 random mountains

In [ ]:
df = df["Mountain"]

random_200_mountains = df.sample(n=200, random_state=42)

In [ ]:
mountain_list = random_200_mountains.tolist()

with open('mountains_names.txt', 'w') as f:
    for mountain in mountain_list:
        f.write(mountain + '\n')